// Generated by `pnpm modules:sync`. Do not edit.
import type { ClientModule } from "./types"
import activities from "./activities/client"
import assignments from "./assignments/client"
import contacts from "./contacts/client"
import docrequests from "./docrequests/client"
import files from "./files/client"
import folders from "./folders/client"
import intake from "./intake/client"
import projects from "./projects/client"
import tasks from "./tasks/client"
import tickets from "./tickets/client"
import users from "./users/client"

export const clientModules: ClientModule[] = [activities, assignments, contacts, docrequests, files, folders, intake, projects, tasks, tickets, users]
