// Generated by `pnpm modules:sync`. Do not edit.
import type { ClientModule } from "./types"
import activity from "./activity/client"
import files from "./files/client"
import projects from "./projects/client"
import users from "./users/client"

export const clientModules: ClientModule[] = [activity, files, projects, users]
