// Generated by `pnpm modules:sync`. Do not edit.
import type { ServerModule } from "./types"
import activities from "./activities/server"
import assignments from "./assignments/server"
import contacts from "./contacts/server"
import docrequests from "./docrequests/server"
import files from "./files/server"
import folders from "./folders/server"
import intake from "./intake/server"
import projects from "./projects/server"
import tasks from "./tasks/server"
import tickets from "./tickets/server"
import users from "./users/server"

export const serverModules: ServerModule[] = [activities, assignments, contacts, docrequests, files, folders, intake, projects, tasks, tickets, users]
