// Generated by `pnpm modules:sync`. Do not edit.
import type { ServerModule } from "./types"
import activity from "./activity/server"
import files from "./files/server"
import projects from "./projects/server"
import users from "./users/server"

export const serverModules: ServerModule[] = [activity, files, projects, users]
