import { sql } from "drizzle-orm"
import {
  boolean,
  check,
  index,
  pgSequence,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core"

/** The only statuses that exist. Anything else is a bug, not a new feature. */
export const TICKET_STATUSES = ["new", "open", "pending", "resolved", "closed"] as const
export const TICKET_PRIORITIES = ["low", "normal", "high", "urgent"] as const

/**
 * Human-quotable references come off a sequence, never off the primary key.
 *
 * A caller who can say "ticket TK000123" needs something short enough to read
 * down a phone line, and a uuid is not that. The reverse — exposing an
 * incrementing primary key — is worse: sequential ids leak how many records
 * exist and let anyone enumerate the table by counting upward. A uuid key plus
 * a separate display sequence gives us both properties.
 *
 * drizzle-kit 0.31 emits `CREATE SEQUENCE` for an exported pgSequence, so the
 * default expression below has something to call by the time the table lands.
 */
export const ticketRefSeq = pgSequence("ticket_ref_seq", { startWith: 1, increment: 1 })

export const tickets = pgTable(
  "tickets",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    /**
     * TK000123. Generated by the database, so two concurrent inserts cannot
     * collide the way a read-then-write in application code would.
     */
    ref: text("ref")
      .notNull()
      .unique()
      .default(sql`'TK' || lpad(nextval('ticket_ref_seq')::text, 6, '0')`),
    subject: text("subject").notNull(),
    status: text("status").notNull().default("new"),
    priority: text("priority").default("normal"),
    requesterId: text("requester_id"),
    assigneeId: text("assignee_id"),
    /** Optional owner record, so a ticket can hang off any table. */
    entityType: text("entity_type"),
    entityId: text("entity_id"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
    closedAt: timestamp("closed_at"),
    /** Soft delete: DELETE stamps this, lists hide it, `:restore` clears it. */
    deletedAt: timestamp("deleted_at"),
  },
  (t) => [
    // The zod schemas reject these too, but a constraint cannot be bypassed by
    // a migration, a fixture or a psql session.
    check(
      "tickets_status_valid",
      sql`${t.status} in ('new', 'open', 'pending', 'resolved', 'closed')`,
    ),
    check("tickets_priority_valid", sql`${t.priority} in ('low', 'normal', 'high', 'urgent')`),
    check("tickets_subject_not_blank", sql`length(trim(${t.subject})) > 0`),
    check("tickets_ref_not_blank", sql`length(trim(${t.ref})) > 0`),
    // A closedAt on an open ticket is a lie every report would repeat, so the
    // database refuses to hold one.
    check(
      "tickets_closed_at_only_when_closed",
      sql`${t.closedAt} is null or ${t.status} = 'closed'`,
    ),
    // Half a polymorphic pointer points nowhere.
    check("tickets_entity_pair_complete", sql`(${t.entityType} is null) = (${t.entityId} is null)`),
    index("tickets_entity_idx").on(t.entityType, t.entityId),
    index("tickets_status_idx").on(t.status, t.createdAt),
  ],
)

export const ticketMessages = pgTable(
  "ticket_messages",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    ticketId: uuid("ticket_id")
      .notNull()
      .references(() => tickets.id),
    authorId: text("author_id"),
    bodyText: text("body_text").notNull(),
    /**
     * Staff-only note. Never leaves the API for a non-staff caller — the
     * filter lives in SQL so a forgotten `.filter()` in a client cannot leak
     * it.
     */
    internal: boolean("internal").notNull().default(false),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    deletedAt: timestamp("deleted_at"),
  },
  (t) => [
    check("ticket_messages_body_not_blank", sql`length(trim(${t.bodyText})) > 0`),
    index("ticket_messages_ticket_idx").on(t.ticketId, t.createdAt),
  ],
)

export type Ticket = typeof tickets.$inferSelect
export type TicketMessage = typeof ticketMessages.$inferSelect
