#!/usr/bin/env tsx
/**
 * Regenerates the module registries from whatever is in src/modules.
 * Runs before dev and build, and after adding or removing a module by hand.
 */
import { readdir, readFile, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import path from "node:path"

import type { ModuleManifest } from "../src/modules/types"

const ROOT = path.resolve(import.meta.dirname, "..")
const MODULES = path.join(ROOT, "src/modules")

export async function readModules(): Promise<ModuleManifest[]> {
  const entries = await readdir(MODULES, { withFileTypes: true })
  const manifests: ModuleManifest[] = []
  for (const e of entries) {
    if (!e.isDirectory()) continue
    const file = path.join(MODULES, e.name, "module.json")
    if (!existsSync(file)) continue

    const manifest: ModuleManifest = JSON.parse(await readFile(file, "utf8"))

    // The folder name is the id: it is what the generated imports point at.
    // A mismatch used to drop the module from the registry in silence — the
    // app booted, the routes were simply gone.
    if (manifest.id !== e.name) {
      throw new Error(
        `src/modules/${e.name}/module.json declares id "${manifest.id}". ` +
          `The id must equal the folder name, or the generated registry imports a path that does not exist.`
      )
    }
    // The id becomes a JS identifier in the generated barrels.
    if (!/^[a-z][a-z0-9]*$/.test(manifest.id)) {
      throw new Error(
        `Module id "${manifest.id}" must be lowercase letters and digits, starting with a letter — ` +
          `it is used as an import name in the generated registries.`
      )
    }

    manifests.push(manifest)
  }
  return manifests.sort((a, b) => a.id.localeCompare(b.id))
}

const banner = "// Generated by `pnpm modules:sync`. Do not edit.\n"

export async function sync() {
  const modules = await readModules()
  const has = (m: ModuleManifest, f: string) => existsSync(path.join(MODULES, m.id, f))

  const server = modules.filter((m) => has(m, "server.ts"))
  const client = modules.filter((m) => has(m, "client.tsx"))
  const schema = modules.filter((m) => has(m, "schema.ts"))

  await writeFile(
    path.join(MODULES, "server.generated.ts"),
    banner +
      `import type { ServerModule } from "./types"\n` +
      server.map((m) => `import ${m.id} from "./${m.id}/server"`).join("\n") +
      `\n\nexport const serverModules: ServerModule[] = [${server.map((m) => m.id).join(", ")}]\n`,
  )

  await writeFile(
    path.join(MODULES, "client.generated.ts"),
    banner +
      `import type { ClientModule } from "./types"\n` +
      client.map((m) => `import ${m.id} from "./${m.id}/client"`).join("\n") +
      `\n\nexport const clientModules: ClientModule[] = [${client.map((m) => m.id).join(", ")}]\n`,
  )

  // drizzle-kit reads this through src/server/db/schema.ts.
  await writeFile(
    path.join(MODULES, "schema.generated.ts"),
    banner + schema.map((m) => `export * from "./${m.id}/schema"`).join("\n") + "\n",
  )

  return { modules, server, client, schema }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { modules } = await sync()
  console.log(
    `synced ${modules.length} module(s): ${modules.map((m) => m.id).join(", ") || "none"}`,
  )
}
